/*
 * Eclipse Scout icon characters - GENERATED FILE, DO NOT EDIT.
 * Extracted from @eclipse-scout/core by tools/extract-scout-icons.mjs.
 * Upstream is licensed under EPL-2.0 - see THIRD-PARTY-NOTICES.md.
 */

/** Maps a Scout icon id (as used in `iconId`, e.g. `font:\uE02A`) to its character in the scoutIcons font. */
export const SCOUT_ICONS: Record<string, string> = {
  'count': '\uFF03',
  'arial-long-arrow-down': '\u2193',
  'arial-long-arrow-up': '\u2191',
  'bullet': '\u2022',
  'exclamation-mark-circle': '\uE001',
  'info': '\uE002',
  'file': '\uE003',
  'calendar': '\uE029',
  'clock': '\uE004',
  'checked-bold': '\uE005',
  'group': '\uE006',
  'group-plus': '\uE007',
  'ellipsis-circle': '\uE008',
  'angle-double-left': '\uE010',
  'angle-double-right': '\uE011',
  'angle-left': '\uE012',
  'angle-right': '\uE013',
  'angle-down': '\uE014',
  'angle-up': '\uE015',
  'long-arrow-down': '\uE016',
  'long-arrow-up': '\uE017',
  'long-arrow-down-plus': '\uE018',
  'long-arrow-up-plus': '\uE019',
  'minus': '\uE01A',
  'plus': '\uE01B',
  'list': '\uE01C',
  'target': '\uE020',
  'world': '\uE021',
  'chart': '\uE022',
  'sum': '\uE02C',
  'avg': '\uE03A',
  'max': '\uE039',
  'max-bold': '\uE027',
  'min': '\uE038',
  'min-bold': '\uE028',
  'gear': '\uE031',
  'star': '\uE02D',
  'star-marked': '\uE02E',
  'star-bold': '\uE032',
  'star-solid': '\uE033',
  'person-solid': '\uE034',
  'remove': '\uE035',
  'expand-all': '\uE036',
  'collapse-all': '\uE037',
  'ellipsis-v': '\uE041',
  'search': '\uE02A',
  'folder': '\uE02B',
  'slippery': '\uE044',
  'remove-bold': '\uE045',
  'pencil': '\uE02F',
  'pencil-underline-solid': '\uE050',
  'rotate-left': '\uE051',
  'rotate-right': '\uE052',
  'hourglass': '\uE053',
  'exclamation-mark-bold': '\uE060',
  'diagram-area': '\uE070',
  'diagram-bar': '\uE071',
  'diagram-bars-horizontal': '\uE072',
  'diagram-bars-vertical': '\uE073',
  'diagram-doughnut': '\uE074',
  'diagram-line': '\uE075',
  'diagram-line-angular': '\uE076',
  'diagram-line-smooth': '\uE077',
  'diagram-pie': '\uE078',
  'diagram-radar': '\uE079',
  'diagram-scatter': '\uE07A',
  'optimize-width': '\uE07B',
  'optimize-widths': '\uE07C',
  'padlock': '\uE07D',
  'chevron-left-bold': '\uF053',
  'chevron-right-bold': '\uF054',
  'plus-bold': '\uF067',
  'minus-bold': '\uF068',
  'chevron-up-bold': '\uF077',
  'chevron-down-bold': '\uF078',
  'square-solid': '\uF0C8',
  'circle-solid': '\uF111',
  'caret-down': '\uF0D7',
  'caret-up': '\uF0D8',
  'caret-left': '\uF0D9',
  'caret-right': '\uF0DA',
  'angle-left-bold': '\uF104',
  'angle-right-bold': '\uF105',
  'angle-up-bold': '\uF106',
  'angle-down-bold': '\uF107',
  'long-arrow-down-bold': '\uF175',
  'long-arrow-up-bold': '\uF176',
  'long-arrow-left-bold': '\uF177',
  'long-arrow-right-bold': '\uF178',
  'arrow-right-bold': '\uF061',
  'sort-amount-desc-bold': '\uF161',
  'sort-alpha-asc-bold': '\uF15D'
};

export const SCOUT_ICON_IDS = Object.keys(SCOUT_ICONS);
